// js/lang.js

const LANGUAGES = [
    { code: 'ar', name: 'Arabic' }, { code: 'bn', name: 'Bengali' }, { code: 'bg', name: 'Bulgarian' }, { code: 'zh', name: 'Chinese Simplified' }, { code: 'zh_tw', name: 'Chinese Traditional' }, { code: 'cs', name: 'Czech' }, { code: 'da', name: 'Danish' }, { code: 'nl', name: 'Dutch' }, { code: 'en', name: 'English' }, { code: 'fi', name: 'Finnish' }, { code: 'fr', name: 'French' }, { code: 'de', name: 'German' }, { code: 'el', name: 'Greek' }, { code: 'hi', name: 'Hindi' }, { code: 'hu', name: 'Hungarian' }, { code: 'it', name: 'Italian' }, { code: 'ja', name: 'Japanese' }, { code: 'jv', name: 'Javanese' }, { code: 'ko', name: 'Korean' }, { code: 'zh_cmn', name: 'Mandarin' }, { code: 'mr', name: 'Marathi' }, { code: 'pl', name: 'Polish' }, { code: 'pt', name: 'Portuguese' }, { code: 'pa', name: 'Punjabi' }, { code: 'ro', name: 'Romanian' }, { code: 'ru', name: 'Russian' }, { code: 'sr', name: 'Serbian' }, { code: 'si', name: 'Sinhalese' }, { code: 'sk', name: 'Slovak' }, { code: 'es', name: 'Spanish' }, { code: 'sv', name: 'Swedish' }, { code: 'ta', name: 'Tamil' }, { code: 'te', name: 'Telugu' }, { code: 'tr', name: 'Turkish' }, { code: 'uk', name: 'Ukrainian' }, { code: 'ur', name: 'Urdu' }, { code: 'vi', name: 'Vietnamese' }, { code: 'zh_wuu', name: 'Wu (Shanghainese)' }, { code: 'zh_hsn', name: 'Xiang' }, { code: 'zh_yue', name: 'Yue (Cantonese)' }, { code: 'zu', name: 'Zulu' }
];

const TRANSLATIONS = {
    'en': { realFeel: 'Real Feel', humidity: 'Humidity', highest: 'Highest', lowest: 'Lowest', windSpeed: 'Wind Speed', visibility: 'Visibility', sevenDayForecast: '7-Day Forecast', forecast: 'Forecast', madeBy: 'Made by Ha Minh Tri', savedLocations: 'Saved Locations', noSavedLocations: 'No saved locations.', chanceOfRain: 'Chance of Rain', uvIndex: 'UV Index', aqi: 'AQI' },
    'vi': { realFeel: 'Cảm giác thực', humidity: 'Độ ẩm', highest: 'Cao nhất', lowest: 'Thấp nhất', windSpeed: 'Tốc độ gió', visibility: 'Tầm nhìn', sevenDayForecast: 'Dự báo 7 ngày', forecast: 'Dự báo', madeBy: 'Thực hiện bởi Hà Minh Trí', savedLocations: 'Địa điểm đã lưu', noSavedLocations: 'Không có địa điểm nào được lưu.', chanceOfRain: 'Khả năng mưa', uvIndex: 'Chỉ số UV', aqi: 'Chỉ số AQI' },
    'es': { realFeel: 'Sensación real', humidity: 'Humedad', highest: 'Más alta', lowest: 'Más bajo', windSpeed: 'Velocidad del viento', visibility: 'Visibilidad', sevenDayForecast: 'Pronóstico de 7 días', forecast: 'Pronóstico', madeBy: 'Hecho por Ha Minh Tri', savedLocations: 'Ubicaciones guardadas', noSavedLocations: 'No hay ubicaciones guardadas.', chanceOfRain: 'Prob. de lluvia', uvIndex: 'Índice UV', aqi: 'ICA' },
    'ar': { realFeel: 'إحساس حقيقي', humidity: 'رطوبة', highest: 'الأعلى', lowest: 'الأدنى', windSpeed: 'سرعة الرياح', visibility: 'رؤية', sevenDayForecast: 'توقعات 7 أيام', forecast: 'توقعات', madeBy: 'صنع بواسطة Ha Minh Tri', savedLocations: 'المواقع المحفوظة', noSavedLocations: 'لا توجد مواقع محفوظة.', chanceOfRain: 'فرصة هطول الأمطار', uvIndex: 'مؤشر الأشعة فوق البنفسجية', aqi: 'مؤشر جودة الهواء' },
    'bn': { realFeel: 'আসল অনুভূতি', humidity: 'আর্দ্রতা', highest: 'সর্বোচ্চ', lowest: ' সর্বনিম্ন', windSpeed: 'বাতাসের গতি', visibility: 'দৃশ্যমানতা', sevenDayForecast: '৭ দিনের পূর্বাভাস', forecast: 'পূর্বাভাস', madeBy: 'Ha Minh Tri দ্বারা তৈরি', savedLocations: 'সংরক্ষিত অবস্থানগুলি', noSavedLocations: 'কোন সংরক্ষিত অবস্থান নেই।', chanceOfRain: 'বৃষ্টির সম্ভাবনা', uvIndex: 'ইউভি সূচক', aqi: 'একিউআই' },
    'bg': { realFeel: 'Усеща се като', humidity: 'Влажност', highest: 'Най-висока', lowest: 'Най-ниска', windSpeed: 'Скорост на вятъра', visibility: 'Видимост', sevenDayForecast: '7-дневна прогноза', forecast: 'Прогноза', madeBy: 'Направено от Ha Minh Tri', savedLocations: 'Запазени местоположения', noSavedLocations: 'Няма запазени местоположения.', chanceOfRain: 'Вероятност за дъжд', uvIndex: 'UV индекс', aqi: 'ИКВ' },
    'zh': { realFeel: '体感温度', humidity: '湿度', highest: '最高', lowest: '最低', windSpeed: '风速', visibility: '能见度', sevenDayForecast: '7天预报', forecast: '预报', madeBy: '由Ha Minh Tri制作', savedLocations: '已保存地点', noSavedLocations: '没有已保存的地点。', chanceOfRain: '降雨概率', uvIndex: '紫外线指数', aqi: '空气质量指数' },
    'zh_tw': { realFeel: '體感溫度', humidity: '濕度', highest: '最高', lowest: '最低', windSpeed: '風速', visibility: '能見度', sevenDayForecast: '7天預報', forecast: '預報', madeBy: '由Ha Minh Tri製作', savedLocations: '已儲存地點', noSavedLocations: '沒有已儲存的地點。', chanceOfRain: '降雨機率', uvIndex: '紫外線指數', aqi: '空氣品質指數' },
    'cs': { realFeel: 'Pocitová teplota', humidity: 'Vlhkost', highest: 'Nejvyšší', lowest: 'Nejnižší', windSpeed: 'Rychlost větru', visibility: 'Viditelnost', sevenDayForecast: '7denní předpověď', forecast: 'Předpověď', madeBy: 'Vytvořil Ha Minh Tri', savedLocations: 'Uložená místa', noSavedLocations: 'Žádná uložená místa.', chanceOfRain: 'Pravděpodobnost deště', uvIndex: 'UV index', aqi: 'Index kvality ovzduší' },
    'da': { realFeel: 'Føles som', humidity: 'Luftfugtighed', highest: 'Højeste', lowest: 'Laveste', windSpeed: 'Vindhastighed', visibility: 'Sigtbarhed', sevenDayForecast: '7-dages vejrudsigt', forecast: 'Vejrudsigt', madeBy: 'Lavet af Ha Minh Tri', savedLocations: 'Gemte placeringer', noSavedLocations: 'Ingen gemte placeringer.', chanceOfRain: 'Regnrisiko', uvIndex: 'UV-indeks', aqi: 'Luftkvalitetsindeks' },
    'nl': { realFeel: 'Gevoelstemperatuur', humidity: 'Vochtigheid', highest: 'Hoogste', lowest: 'Laagste', windSpeed: 'Windsnelheid', visibility: 'Zichtbaarheid', sevenDayForecast: '7-daagse voorspelling', forecast: 'Voorspelling', madeBy: 'Gemaakt door Ha Minh Tri', savedLocations: 'Opgeslagen locaties', noSavedLocations: 'Geen opgeslagen locaties.', chanceOfRain: 'Kans op regen', uvIndex: 'UV-index', aqi: 'Luchtkwaliteitsindex' },
    'fi': { realFeel: 'Tuntuu kuin', humidity: 'Kosteus', highest: 'Korkein', lowest: 'Matalin', windSpeed: 'Tuulen nopeus', visibility: 'Näkyvyys', sevenDayForecast: '7 päivän ennuste', forecast: 'Ennuste', madeBy: 'Tekijä: Ha Minh Tri', savedLocations: 'Tallennetut sijainnit', noSavedLocations: 'Ei tallennettuja sijainteja.', chanceOfRain: 'Sateen mahdollisuus', uvIndex: 'UV-indeksi', aqi: 'Ilmanlaatuindeksi' },
    'fr': { realFeel: 'Ressenti', humidity: 'Humidité', highest: 'Maximale', lowest: 'Minimale', windSpeed: 'Vitesse du vent', visibility: 'Visibilité', sevenDayForecast: 'Prévisions sur 7 jours', forecast: 'Prévisions', madeBy: 'Fait par Ha Minh Tri', savedLocations: 'Lieux enregistrés', noSavedLocations: 'Aucun lieu enregistré.', chanceOfRain: 'Risque de pluie', uvIndex: 'Indice UV', aqi: 'IQA' },
    'de': { realFeel: 'Gefühlte Temp.', humidity: 'Luftfeuchtigkeit', highest: 'Höchst', lowest: 'Tiefst', windSpeed: 'Windgeschw.', visibility: 'Sichtweite', sevenDayForecast: '7-Tage-Vorhersage', forecast: 'Vorhersage', madeBy: 'Erstellt von Ha Minh Tri', savedLocations: 'Gespeicherte Orte', noSavedLocations: 'Keine gespeicherten Orte.', chanceOfRain: 'Regenwahrscheinlichkeit', uvIndex: 'UV-Index', aqi: 'Luftqualitätsindex' },
    'el': { realFeel: 'Αισθητή θερμ.', humidity: 'Υγρασία', highest: 'Μέγιστη', lowest: 'Ελάχιστη', windSpeed: 'Ταχύτητα ανέμου', visibility: 'Ορατότητα', sevenDayForecast: 'Πρόγνωση 7 ημερών', forecast: 'Πρόγνωση', madeBy: 'Από Ha Minh Tri', savedLocations: 'Αποθηκευμένες τοποθεσίες', noSavedLocations: 'Δεν υπάρχουν αποθηκευμένες τοποθεσίες.', chanceOfRain: 'Πιθανότητα βροχής', uvIndex: 'Δείκτης UV', aqi: 'Δείκτης Ποιότητας Αέρα' },
    'hi': { realFeel: 'वास्तविक महसूस', humidity: 'नमी', highest: 'उच्चतम', lowest: 'न्यूनतम', windSpeed: 'हवा की गति', visibility: 'दृश्यता', sevenDayForecast: '7-दिन का पूर्वानुमान', forecast: 'पूर्वानुमान', madeBy: 'Ha Minh Tri द्वारा बनाया गया', savedLocations: 'सहेजे गए स्थान', noSavedLocations: 'कोई सहेजा गया स्थान नहीं।', chanceOfRain: 'बारिश की संभावना', uvIndex: 'यूवी इंडेक्स', aqi: 'एक्यूआई' },
    'hu': { realFeel: 'Hőérzet', humidity: 'Páratartalom', highest: 'Legmagasabb', lowest: 'Legalacsonyabb', windSpeed: 'Szélsebesség', visibility: 'Látótávolság', sevenDayForecast: '7 napos előrejelzés', forecast: 'Előrejelzés', madeBy: 'Készítette: Ha Minh Tri', savedLocations: 'Mentett helyek', noSavedLocations: 'Nincsenek mentett helyek.', chanceOfRain: 'Eső esélye', uvIndex: 'UV-index', aqi: 'Levegőminőségi index' },
    'it': { realFeel: 'Percepita', humidity: 'Umidità', highest: 'Massima', lowest: 'Minima', windSpeed: 'Velocità del vento', visibility: 'Visibilità', sevenDayForecast: 'Previsioni a 7 giorni', forecast: 'Previsioni', madeBy: 'Creato da Ha Minh Tri', savedLocations: 'Luoghi salvati', noSavedLocations: 'Nessun luogo salvato.', chanceOfRain: 'Probabilità di pioggia', uvIndex: 'Indice UV', aqi: 'IQA' },
    'ja': { realFeel: '体感温度', humidity: '湿度', highest: '最高', lowest: '最低', windSpeed: '風速', visibility: '視程', sevenDayForecast: '7日間予報', forecast: '予報', madeBy: '作成者 Ha Minh Tri', savedLocations: '保存した場所', noSavedLocations: '保存した場所はありません。', chanceOfRain: '降水確率', uvIndex: 'UV指数', aqi: '空気質指数' },
    'jv': { realFeel: 'Krasa Nyata', humidity: 'Kelembapan', highest: 'Paling Dhuwur', lowest: 'Paling Endhek', windSpeed: 'Kacepetan Angin', visibility: 'Jarak Pandang', sevenDayForecast: 'Prakiraan 7 Dina', forecast: 'Prakiraan', madeBy: 'Digawe dening Ha Minh Tri', savedLocations: 'Lokasi sing Disimpen', noSavedLocations: 'Ora ana lokasi sing disimpen.', chanceOfRain: 'K kemungkinan udan', uvIndex: 'Indeks UV', aqi: 'Indeks Kualitas Udara' },
    'ko': { realFeel: '체감 온도', humidity: '습도', highest: '최고', lowest: '최저', windSpeed: '풍속', visibility: '가시거리', sevenDayForecast: '7일 예보', forecast: '예보', madeBy: '제작자: Ha Minh Tri', savedLocations: '저장된 위치', noSavedLocations: '저장된 위치가 없습니다.', chanceOfRain: '강수 확률', uvIndex: '자외선 지수', aqi: '대기질 지수' },
    'zh_cmn': { realFeel: '体感温度', humidity: '湿度', highest: '最高', lowest: '最低', windSpeed: '风速', visibility: '能见度', sevenDayForecast: '7天预报', forecast: '预报', madeBy: '由Ha Minh Tri制作', savedLocations: '已保存地点', noSavedLocations: '没有已保存的地点。', chanceOfRain: '降雨概率', uvIndex: '紫外线指数', aqi: '空气质量指数' },
    'mr': { realFeel: 'वास्तविक احساس', humidity: 'आर्द्रता', highest: 'सर्वोच्च', lowest: 'सर्वात कमी', windSpeed: 'वाऱ्याचा वेग', visibility: 'दृश्यमानता', sevenDayForecast: '७-दिवसांचा अंदाज', forecast: 'अंदाज', madeBy: 'Ha Minh Tri यांनी बनवले', savedLocations: 'जतन केलेली ठिकाणे', noSavedLocations: 'कोणतीही जतन केलेली ठिकाणे नाहीत.', chanceOfRain: 'पावसाची शक्यता', uvIndex: 'यूव्ही निर्देशांक', aqi: 'एअर क्वालिटी इंडेक्स' },
    'pl': { realFeel: 'Odczuwalna', humidity: 'Wilgotność', highest: 'Najwyższa', lowest: 'Najniższa', windSpeed: 'Prędkość wiatru', visibility: 'Widoczność', sevenDayForecast: '7-dniowa prognoza', forecast: 'Prognoza', madeBy: 'Stworzone przez Ha Minh Tri', savedLocations: 'Zapisane lokalizacje', noSavedLocations: 'Brak zapisanych lokalizacji.', chanceOfRain: 'Szansa na deszcz', uvIndex: 'Indeks UV', aqi: 'AQI' },
    'pt': { realFeel: 'Sensação real', humidity: 'Umidade', highest: 'Máxima', lowest: 'Mínima', windSpeed: 'Veloc. do vento', visibility: 'Visibilidade', sevenDayForecast: 'Previsão de 7 dias', forecast: 'Previsão', madeBy: 'Feito por Ha Minh Tri', savedLocations: 'Locais salvos', noSavedLocations: 'Nenhum local salvo.', chanceOfRain: 'Chance de chuva', uvIndex: 'Índice UV', aqi: 'IQA' },
    'pa': { realFeel: 'ਅਸਲ ਮਹਿਸੂਸ', humidity: 'ਨਮੀ', highest: 'ਸਭ ਤੋਂ ਵੱਧ', lowest: 'ਸਭ ਤੋਂ ਘੱਟ', windSpeed: 'ਹਵਾ ਦੀ ਗਤੀ', visibility: 'ਦ੍ਰਿਸ਼ਟੀ', sevenDayForecast: '7-ਦਿਨ ਦੀ ਭਵਿੱਖਬਾਣੀ', forecast: 'ਭਵਿੱਖਬਾਣੀ', madeBy: 'Ha Minh Tri ਦੁਆਰਾ ਬਣਾਇਆ ਗਿਆ', savedLocations: 'ਸੁਰੱਖਿਅਤ ਕੀਤੇ ਟਿਕਾਣੇ', noSavedLocations: 'ਕੋਈ ਸੁਰੱਖਿਅਤ ਕੀਤੇ ਟਿਕਾਣੇ ਨਹੀਂ।', chanceOfRain: 'ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ', uvIndex: 'ਯੂਵੀ ਇੰਡੈਕਸ', aqi: 'AQI' },
    'ro': { realFeel: 'Se simte ca', humidity: 'Umiditate', highest: 'Maximă', lowest: 'Minimă', windSpeed: 'Viteza vântului', visibility: 'Vizibilitate', sevenDayForecast: 'Prognoză pe 7 zile', forecast: 'Prognoză', madeBy: 'Realizat de Ha Minh Tri', savedLocations: 'Locații salvate', noSavedLocations: 'Nicio locație salvată.', chanceOfRain: 'Șanse de ploaie', uvIndex: 'Indice UV', aqi: 'IQA' },
    'ru': { realFeel: 'Ощущается как', humidity: 'Влажность', highest: 'Макс.', lowest: 'Мин.', windSpeed: 'Скорость ветра', visibility: 'Видимость', sevenDayForecast: 'Прогноз на 7 дней', forecast: 'Прогноз', madeBy: 'Сделано Ha Minh Tri', savedLocations: 'Сохраненные места', noSavedLocations: 'Нет сохраненных мест.', chanceOfRain: 'Вероятность дождя', uvIndex: 'УФ-индекс', aqi: 'ИКВ' },
    'sr': { realFeel: 'Субјективни осећај', humidity: 'Влажност', highest: 'Највиша', lowest: 'Најнижа', windSpeed: 'Брзина ветра', visibility: 'Видљивост', sevenDayForecast: 'Прогноза за 7 дана', forecast: 'Прогноза', madeBy: 'Направио Ha Minh Tri', savedLocations: 'Сачуване локације', noSavedLocations: 'Нема сачуваних локација.', chanceOfRain: 'Вероватноћа кише', uvIndex: 'УВ индекс', aqi: 'ИКА' },
    'si': { realFeel: 'සැබෑ දැනීම', humidity: 'ආර්ද්රතාවය', highest: 'ඉහළම', lowest: 'අඩුම', windSpeed: 'සුළං වේගය', visibility: 'දෘශ්‍යතාව', sevenDayForecast: 'දින 7ක අනාවැකිය', forecast: 'අනාවැකිය', madeBy: 'Ha Minh Tri විසින් සාදන ලදී', savedLocations: 'සුරකින ලද ස්ථාන', noSavedLocations: 'සුරකින ලද ස්ථාන නොමැත.', chanceOfRain: 'වර්ෂාපතන සම්භාවිතාව', uvIndex: 'UV දර්ශකය', aqi: 'වායු ගුණාත්මක දර්ශකය' },
    'sk': { realFeel: 'Pocitová teplota', humidity: 'Vlhkosť', highest: 'Najvyššia', lowest: 'Najnižšia', windSpeed: 'Rýchlosť vetra', visibility: 'Viditeľnosť', sevenDayForecast: '7-dňová predpoveď', forecast: 'Predpoveď', madeBy: 'Vytvoril Ha Minh Tri', savedLocations: 'Uložené miesta', noSavedLocations: 'Žiadne uložené miesta.', chanceOfRain: 'Šanca na dážď', uvIndex: 'UV index', aqi: 'Index kvality ovzdušia' },
    'sv': { realFeel: 'Känns som', humidity: 'Luftfuktighet', highest: 'Högsta', lowest: 'Lägsta', windSpeed: 'Vindhastighet', visibility: 'Sikt', sevenDayForecast: '7-dygnsprognos', forecast: 'Prognos', madeBy: 'Gjord av Ha Minh Tri', savedLocations: 'Sparade platser', noSavedLocations: 'Inga sparade platser.', chanceOfRain: 'Risk för regn', uvIndex: 'UV-index', aqi: 'Luftkvalitetsindex' },
    'ta': { realFeel: 'உண்மையான உணர்வு', humidity: 'ஈரப்பதம்', highest: 'அதிகபட்சம்', lowest: 'குறைந்தபட்சம்', windSpeed: 'காற்றின் வேகம்', visibility: 'பார்வை', sevenDayForecast: '7-நாள் முன்னறிவிப்பு', forecast: 'முன்னறிவிப்பு', madeBy: 'Ha Minh Tri ஆல் உருவாக்கப்பட்டது', savedLocations: 'சேமிக்கப்பட்ட இடங்கள்', noSavedLocations: 'சேமிக்கப்பட்ட இடங்கள் இல்லை.', chanceOfRain: 'மழைக்கான வாய்ப்பு', uvIndex: 'UV குறியீடு', aqi: 'காற்றின் தரக் குறியீடு' },
    'te': { realFeel: 'నిజమైన అనుభూతి', humidity: 'తేమ', highest: 'అత్యధికం', lowest: 'అత్యల్పం', windSpeed: 'గాలి వేగం', visibility: 'దృశ్యమానత', sevenDayForecast: '7-రోజుల సూచన', forecast: 'సూచన', madeBy: 'Ha Minh Tri చే తయారు చేయబడింది', savedLocations: 'సేవ్ చేయబడిన స్థానాలు', noSavedLocations: 'సేవ్ చేయబడిన స్థానాలు లేవు.', chanceOfRain: 'వర్షం యొక్క అవకాశం', uvIndex: 'UV సూచిక', aqi: 'గాలి నాణ్యత సూచిక' },
    'tr': { realFeel: 'Hissedilen', humidity: 'Nem', highest: 'En yüksek', lowest: 'En düşük', windSpeed: 'Rüzgar hızı', visibility: 'Görüş', sevenDayForecast: '7 günlük tahmin', forecast: 'Tahmin', madeBy: 'Yapan: Ha Minh Tri', savedLocations: 'Kayıtlı Konumlar', noSavedLocations: 'Kayıtlı konum yok.', chanceOfRain: 'Yağmur İhtimali', uvIndex: 'UV İndeksi', aqi: 'Hava Kalitesi İndeksi' },
    'uk': { realFeel: 'Відчувається як', humidity: 'Вологість', highest: 'Найвища', lowest: 'Найнижча', windSpeed: 'Швидкість вітру', visibility: 'Видимість', sevenDayForecast: 'Прогноз на 7 днів', forecast: 'Прогноз', madeBy: 'Зроблено Ha Minh Tri', savedLocations: 'Збережені місця', noSavedLocations: 'Немає збережених місць.', chanceOfRain: 'Ймовірність дощу', uvIndex: 'УФ-індекс', aqi: 'Індекс якості повітря' },
    'ur': { realFeel: 'حقیقی احساس', humidity: 'نمی', highest: 'زیادہ سے زیادہ', lowest: 'کم سے کم', windSpeed: 'ہوا کی رفتار', visibility: 'မြင်ibilité', sevenDayForecast: '7 دن کی پیشن گوئی', forecast: 'پیشن گوئی', madeBy: 'Ha Minh Tri نے بنایا', savedLocations: 'محفوظ کردہ مقامات', noSavedLocations: 'کوئی محفوظ کردہ مقامات نہیں ہیں۔', chanceOfRain: 'بارش کا امکان', uvIndex: 'یووی انڈیکس', aqi: 'AQI' },
    'zh_wuu': { realFeel: '体感温度', humidity: '湿度', highest: '最高', lowest: '最低', windSpeed: '风速', visibility: '能见度', sevenDayForecast: '7天预报', forecast: '预报', madeBy: '由Ha Minh Tri制作', savedLocations: '已保存地点', noSavedLocations: '没有已保存的地点。', chanceOfRain: '降雨概率', uvIndex: '紫外线指数', aqi: '空气质量指数' },
    'zh_hsn': { realFeel: '体感温度', humidity: '湿度', highest: '最高', lowest: '最低', windSpeed: '风速', visibility: '能见度', sevenDayForecast: '7天预报', forecast: '预报', madeBy: '由Ha Minh Tri制作', savedLocations: '已保存地点', noSavedLocations: '没有已保存的地点。', chanceOfRain: '降雨概率', uvIndex: '紫外线指数', aqi: '空气质量指数' },
    'zh_yue': { realFeel: '體感溫度', humidity: '濕度', highest: '最高', lowest: '最低', windSpeed: '風速', visibility: '能見度', sevenDayForecast: '7日天氣預報', forecast: '天氣預報', madeBy: '由Ha Minh Tri製作', savedLocations: '已儲存地點', noSavedLocations: '沒有已儲รวจ的地點。', chanceOfRain: '降雨機率', uvIndex: '紫外線指數', aqi: '空氣品質指數' },
    'zu': { realFeel: 'Kuzwakala Njengokwangempela', humidity: 'Umswakama', highest: 'Phezulu Kakhulu', lowest: 'Phansi Kakhulu', windSpeed: 'Isivinini Somoya', visibility: 'Ukubonakala', sevenDayForecast: 'Isibikezelo Sezinsuku Eziyi-7', forecast: 'Isibikezelo', madeBy: 'Kwenziwe ngu-Ha Minh Tri', savedLocations: 'Izindawo Ezilondoloziwe', noSavedLocations: 'Azikho izindawo ezilondoloziwe.', chanceOfRain: 'Ithuba Lemvula', uvIndex: 'Inkomba ye-UV', aqi: 'I-AQI' }
};

function updateStaticText(lang) {
    const langTranslations = TRANSLATIONS[lang] || TRANSLATIONS['en'];
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.dataset.key;
        if (langTranslations[key]) {
            if (element.tagName === 'SPAN' && element.parentElement.tagName === 'A') {
                element.textContent = ' ' + langTranslations[key];
            } else {
                const suffix = element.classList.contains('real-feel-additional-label') || element.classList.contains('humidity-additional-label') || element.classList.contains('max-temperature-additional-label') || element.classList.contains('min-temperature-additional-label') || element.classList.contains('wind-speed-additional-label') || element.classList.contains('visibility-additional-label') || element.classList.contains('rain-chance-additional-label') || element.classList.contains('uv-index-additional-label') || element.classList.contains('aqi-additional-label') ? ' ' : '';
                element.textContent = langTranslations[key] + suffix;
            }
        }
    });
}